import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { AppSidebar } from "@/components/app-sidebar";
import { ModelProvider } from "@/lib/contexts/model-context";
import { ProjectProvider } from "@/lib/contexts/project-context";
import { Suspense } from "react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen overflow-hidden`}
      >
        <Suspense fallback={<div>Loading...</div>}>
          <div className="flex h-full w-full">
            <ModelProvider>
              <ProjectProvider>
                <AppSidebar />
                <main className="flex-1 flex flex-col h-screen overflow-hidden bg-slate-50 dark:bg-slate-900">
                  <div className="flex-1 overflow-auto">
                    {children}
                  </div>
                </main>
              </ProjectProvider>
            </ModelProvider>
          </div>
        </Suspense>
        <Toaster />
      </body>
    </html>
  );
}
